version: '3'

tasks:
  default:
    - task: prepare

  build_dialog:
    dir: vendor/threadi/easy-dialog-for-wordpress/
    cmds:
      - npm i
      - npm run build

  build_directory:
    dir: vendor/threadi/easy-setup-for-wordpress/
    cmds:
      - npm i
      - npm run build

  prepare:
    cmds:
      - composer install
      - composer update
      - npm i
      - npm run build
      - task: build_dialog
      - task: build_directory

  check:
    cmds:
      - vendor/bin/phpstan analyse
      - vendor/bin/phpcbf --standard=ruleset.xml .
      - vendor/bin/phpcs --standard=ruleset.xml .

  build_zip:
    dir: ../
    cmds:
      - zip -rq external-files-in-media-library/releases/external-files-in-media-library_{{.CLI_ARGS}}.zip external-files-in-media-library/ -x "*/.git/*" "*/.github/*" "*/blocks/*/src/*" "*/docs/*" "*/phpcs.xml" "*/composer.json" "*/composer.lock" "*/package.json" "*/package-lock.json" "*/ruleset.xml" "*/.gitignore" "*/vendor/*" "*/node_modules/*" "*/.editorconfig" "*/build/*" "*/releases/*" "*/svn/*" "*/languages/*" "*/changelog.md" "*/readme.md" "*/ruleset.xml" "*/assets/*" "*/external-files-in-media-library-dev.php" "*/readme-dev.txt" "*/phpstan.neon" "*/Taskfile.yml" "*/libs/*" "*/src/*"
      - zip -urq external-files-in-media-library/releases/external-files-in-media-library_{{.CLI_ARGS}}.zip external-files-in-media-library/vendor/autoload.php
      - zip -urq external-files-in-media-library/releases/external-files-in-media-library_{{.CLI_ARGS}}.zip external-files-in-media-library/vendor/composer/*
      - zip -urq external-files-in-media-library/releases/external-files-in-media-library_{{.CLI_ARGS}}.zip external-files-in-media-library/vendor/gettext/*
      - zip -urq external-files-in-media-library/releases/external-files-in-media-library_{{.CLI_ARGS}}.zip external-files-in-media-library/vendor/threadi/*/build/*
      - zip -urq external-files-in-media-library/releases/external-files-in-media-library_{{.CLI_ARGS}}.zip external-files-in-media-library/vendor/threadi/*/lib/*

  release:
    cmds:
      - task: prepare
      - composer dump-autoload -oa --no-dev
      - task: check
      - cp easy-language.php easy-language-dev.php
      - sed -i -e 's/@@VersionNumber@@/{{.CLI_ARGS}}/g' easy-language.php
      - cp readme.txt readme-dev.txt
      - sed -i -e 's/@@VersionNumber@@/{{.CLI_ARGS}}/g' readme.txt
      - rm -f releases/easy-language_{{.CLI_ARGS}}.zip
      - task: build_zip
      - mv easy-language-dev.php easy-language.php
      - mv readme-dev.txt readme.txt
      - echo 'Release file generated'
